# Generated by Django 2.2.1 on 2019-06-04 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190604_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wish_list',
        ),
        migrations.AlterField(
            model_name='join',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='myapp.Item'),
        ),
        migrations.AlterField(
            model_name='join',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='myapp.User'),
        ),
    ]
